### ISSUE TITLE
24-02-01-thu : vue. 이창호교수님

### ISSUE THREAD

**Issue by 2sjdeveloper** [2sjdeveloper/webWorkSpace#6]
### 1교시
- MVVM 패턴
- 프로그램 추가하기.
- 폴더 생성
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/e235fecb-cd32-45de-8d4d-42afeae8465b)

- 명령프롬프트에서 D:\Dev\vue-workspace 로 이동 후(vue-workspace가 설치된 곳으로 이동하면 됨) 책 44쪽부터 실행(아래 코드 순서)
1. `npm install -g @vue/cli`
2. `vue`
3. `vue create vue-project`
4. 버전 3 선택 -> 폴더 안에 이것저것 파일들 생성됨.
- vue 프로젝트 생성(47쪽)
1. `npm run serve`
2. 명령프롬프트에서 로컬 포트 참고하여 주소창에 입력

**Comment by 2sjdeveloper** [comment]
- 비주얼에서 vue-project 폴더 열어줌 
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/4bf79683-b847-4dd2-851d-dcc70d97656f)

- 자동으로 생성되어있는 파일들 살펴봄. 그때 봐야하는 순서.
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/32abea1b-46e0-4b1a-8df8-6709c0766757)

- 이거 설치
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/f9906c68-f98b-4dc7-b45c-561c81b7530e)

**Comment by 2sjdeveloper** [comment]
### 2교시 
- http://localhost:8081/ 화면과 이것들 보는중
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/b6719498-1de4-46a3-9b48-66d8e71fbfad)

- 책 46~48쪽

- 명령프롬프트에서 기존 작업 끝내고(컨트롤+C) vue-project로 폴더 이동해서 새 프로젝트 생성해보기(책 51쪽~)

- 생성하고 비주얼에서 오픈 폴더 -> vue-project-manually 열기
- 명령프롬프트에서 실행
```
D:\Dev\vue-workspace>cd vue-project-manually

D:\Dev\vue-workspace\vue-project-manually>npm run serve

> vue-project-manually@0.1.0 serve
> vue-cli-service serve

 INFO  Starting development server...


 DONE  Compiled successfully in 2764ms                                                                     오전 10:25:23


  App running at:
  - Local:   http://localhost:8081/
  - Network: http://192.168.0.33:8081/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```
http://localhost:8081/

**Comment by 2sjdeveloper** [comment]
- 책 57쪽~ 
- GUI 환경에서 새 프로젝트 만들기 (책 따라서 만들기)
세가지 버전으로 프로젝트 만들기 해봤음.
- 다시 명령프롬프트에서 vue-project 로 다시 돌아와서 `npm run serve` 해줌

- 명령 프롬프트 하나 더 열어서 라우터 설치(책 73쪽~)
```
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\admin>cd /

C:\>cd d:
D:\

C:\>d:

D:\>cd dev

D:\Dev>cd vue-workspace

D:\Dev\vue-workspace>vue add router

📦  Installing @vue/cli-plugin-router...


added 114 packages in 3s

20 packages are looking for funding
  run `npm fund` for details
✔  Successfully installed plugin: @vue/cli-plugin-router

? Use history mode for router? (Requires proper server setup for index fallback in production) Yes

🚀  Invoking generator for @vue/cli-plugin-router...
 ERROR  Error: Cannot find module '@vue/cli-service/generator/template/src/App.vue' from 'D:\Dev\vue-workspace\node_modules\@vue\cli-plugin-router\generator\template\src'
Error: Cannot find module '@vue/cli-service/generator/template/src/App.vue' from 'D:\Dev\vue-workspace\node_modules\@vue\cli-plugin-router\generator\template\src'
    at Function.resolveSync [as sync] (C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\resolve\lib\sync.js:111:15)
    at renderFile (C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\GeneratorAPI.js:518:17)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\GeneratorAPI.js:303:27
    at async Generator.resolveFiles (C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:313:7)
    at async Generator.generate (C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:205:5)
    at async runGenerator (C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)
    at async invoke (C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)

D:\Dev\vue-workspace>cd vue-project

D:\Dev\vue-workspace\vue-project>vue add router
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing @vue/cli-plugin-router...


up to date, audited 970 packages in 3s

110 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
✔  Successfully installed plugin: @vue/cli-plugin-router

? Use history mode for router? (Requires proper server setup for index fallback in production) Yes

🚀  Invoking generator for @vue/cli-plugin-router...
📦  Installing additional dependencies...


added 2 packages, and audited 972 packages in 1s

111 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
⚓  Running completion hooks...

✔  Successfully invoked generator for plugin: @vue/cli-plugin-router

D:\Dev\vue-workspace\vue-project>
```

**Comment by 2sjdeveloper** [comment]
- 이거 다시 열어줌 
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/a44a15ae-145a-4e59-9a3a-2af0f4354edd)

**Comment by 2sjdeveloper** [comment]
- 여기서 데이터 바인딩 추가.
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/ded4d772-4ac4-41fe-b67c-8524d150ea5d)

**Comment by 2sjdeveloper** [comment]
### 3교시
- 2교시 이어서
- 뷰 폴더 안에 데이터바인딩.뷰 파일 생성
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/41bc7d4a-7699-48fd-81bf-e8c59ef16c20)

- 복사,붙여넣기해서 2 만듦
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/d8aaffcf-80de-4a00-a092-9073404eb697)

**Comment by 2sjdeveloper** [comment]
### 4교시
- 3교시 이어서 데이터바인딩1,2 파일들에 이것저것 입력..
- 아까처럼 데이터바인딩2 복붙해서 데이터바인딩3 파일 만듦.
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/bb2a896b-6b58-444c-8e30-205f7a2787c2)
- 새로 파일 만들때마다 저기서 입력값 2, 3 으로 바꿔줘야됨(도메인값과 연결해주기 위함)
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/d7bec9bb-25fe-47b6-a12f-ff1bf6fbab60)

**Comment by 2sjdeveloper** [comment]
### 5교시
- 3 복붙해서 DataBinding4.vue 만들고 라우트값도 4로 바꿔줌.
- 책 91쪽

- AboutView.vue 복붙해서 이름은 DataBidingList.vue로 바꿈

**Comment by 2sjdeveloper** [comment]
### 6교시

**Comment by 2sjdeveloper** [comment]
### 7교시
- 책 116쪽~
- 이벤트 처리
- EventClick.vue 파일 생성
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/2f728989-6237-43e8-9b06-7436a2921e7a)

-EventTodo.vue 파일 생성
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/97f5ed55-acee-47eb-8087-00f1ae2e775f)

**Comment by 2sjdeveloper** [comment]
### 8교시
- 책 120쪽~
- ComputedView.vue 파일 생성 
![image](https://github.com/2sjdeveloper/webWorkSpace/assets/152113934/b7a268fd-7ebc-431e-b803-2f686b633c66)

- 안되면 서버 종료(컨트롤+C) 하고 다시 시작 `npm run serve`
